{
    "vehicles" [
      {"car_name": "Model S", "brand": "Tesla", "price": 79999, "color": "Red", "image": "https://example.com/tesla-model-s.jpg"},
      {"car_name": "Model S", "brand": "Tesla", "price": 79999, "color": "Red", "image": "https://example.com/tesla-model-s.jpg"},
      {"car_name": "Model S", "brand": "Tesla", "price": 79999, "color": "Red", "image": "https://example.com/tesla-model-s.jpg"},
      {"car_name": "Mustang", "brand": "Ford", "price": 55999, "color": "Blue", "image": "https://example.com/ford-mustang.jpg"},
      {"car_name": "Civic", "brand": "Honda", "price": 24999, "color": "Black", "image": "https://example.com/honda-civic.jpg"},
      {"car_name": "Corolla", "brand": "Toyota", "price": 23999, "color": "White", "image": "https://example.com/toyota-corolla.jpg"},
      {"car_name": "Camry", "brand": "Toyota", "price": 27999, "color": "Silver", "image": "https://example.com/toyota-camry.jpg"},
      {"car_name": "Accord", "brand": "Honda", "price": 28999, "color": "Gray", "image": "https://example.com/honda-accord.jpg"},
      {"car_name": "X5", "brand": "BMW", "price": 60999, "color": "Black", "image": "https://example.com/bmw-x5.jpg"},
      {"car_name": "A4", "brand": "Audi", "price": 42999, "color": "Blue", "image": "https://example.com/audi-a4.jpg"},
      {"car_name": "C-Class", "brand": "Mercedes-Benz", "price": 45999, "color": "White", "image": "https://example.com/mercedes-c-class.jpg"},
      {"car_name": "Altima", "brand": "Nissan", "price": 25999, "color": "Red", "image": "https://example.com/nissan-altima.jpg"},
      {"car_name": "Challenger", "brand": "Dodge", "price": 58999, "color": "Yellow", "image": "https://example.com/dodge-challenger.jpg"},
      {"car_name": "Cherokee", "brand": "Jeep", "price": 34999, "color": "Green", "image": "https://example.com/jeep-cherokee.jpg"},
      {"car_name": "Tucson", "brand": "Hyundai", "price": 30999, "color": "Gray", "image": "https://example.com/hyundai-tucson.jpg"},
      {"car_name": "Elantra", "brand": "Hyundai", "price": 22999, "color": "White", "image": "https://example.com/hyundai-elantra.jpg"},
      {"car_name": "RX", "brand": "Lexus", "price": 50999, "color": "Silver", "image": "https://example.com/lexus-rx.jpg"},
      {"car_name": "Range Rover", "brand": "Land Rover", "price": 90999, "color": "Black", "image": "https://example.com/land-rover-range-rover.jpg"},
      {"car_name": "Outback", "brand": "Subaru", "price": 32999, "color": "Brown", "image": "https://example.com/subaru-outback.jpg"},
      {"car_name": "Impreza", "brand": "Subaru", "price": 22999, "color": "Blue", "image": "https://example.com/subaru-impreza.jpg"},
      {"car_name": "Tiguan", "brand": "Volkswagen", "price": 33999, "color": "White", "image": "https://example.com/vw-tiguan.jpg"},
      {"car_name": "Golf", "brand": "Volkswagen", "price": 24999, "color": "Red", "image": "https://example.com/vw-golf.jpg"},
      {"car_name": "Chiron", "brand": "Bugatti", "price": 2999999, "color": "Blue", "image": "https://example.com/bugatti-chiron.jpg"},
      {"car_name": "Veyron", "brand": "Bugatti", "price": 1999999, "color": "Black", "image": "https://example.com/bugatti-veyron.jpg"},
      {"car_name": "Ghibli", "brand": "Maserati", "price": 74999, "color": "Gray", "image": "https://example.com/maserati-ghibli.jpg"},
      {"car_name": "Levante", "brand": "Maserati", "price": 82999, "color": "White", "image": "https://example.com/maserati-levante.jpg"},
      {"car_name": "XC90", "brand": "Volvo", "price": 57999, "color": "Silver", "image": "https://example.com/volvo-xc90.jpg"},
      {"car_name": "S90", "brand": "Volvo", "price": 50999, "color": "Black", "image": "https://example.com/volvo-s90.jpg"},
      {"car_name": "DB11", "brand": "Aston Martin", "price": 219999, "color": "Green", "image": "https://example.com/aston-martin-db11.jpg"},
      {"car_name": "Huracan", "brand": "Lamborghini", "price": 249999, "color": "Yellow", "image": "https://example.com/lamborghini-huracan.jpg"},
      {"car_name": "911", "brand": "Porsche", "price": 129999, "color": "Blue", "image": "https://example.com/porsche-911.jpg"}
    ]
  }
  