
    const carsData = [
      {"car_name": "Model 3", "brand": "Tesla", "price": 79999, "color": "Red", "image": "/images/Tesla-Model-3-Red.webp"},
      {"car_name": "Model S", "brand": "Tesla", "price": 89999, "color": "Blue", "image": "/images/Tesla-Model-S-Blue.webp"},
      {"car_name": "Model Y", "brand": "Tesla", "price": 69999, "color": "White", "image": "/images/Tesla-Model-Y-White.webp"},
      {"car_name": "Mustang", "brand": "Ford", "price": 55999, "color": "Black", "image": "/images/Mustang-Black.webp"},
      {"car_name": "Mustang", "brand": "Ford", "price": 75999, "color": "Red", "image": "/images/Mustang-Red.webp"},
      {"car_name": "Mustang", "brand": "Ford", "price": 85999, "color": "Yellow", "image": "/images/Mustang-Yellow.webp"},
      {"car_name": "Civic", "brand": "Honda", "price": 24999, "color": "Blue", "image": "/images/Civic-Blue.webp"},
      {"car_name": "Civic", "brand": "Honda", "price": 23999, "color": "Grey", "image": "/images/Civic-Grey.webp"},
      {"car_name": "Civic", "brand": "Honda", "price": 24899, "color": "Red", "image": "/images/Civic-Red.webp"},
      {"car_name": "Corolla", "brand": "Toyota", "price": 23699, "color": "Blue", "image": "/images/Toyota-Blue.webp"},
      {"car_name": "Corolla", "brand": "Toyota", "price": 43999, "color": "Red", "image": "/images/Toyota-Red.webp"},
      {"car_name": "Corolla", "brand": "Toyota", "price": 30999, "color": "White", "image": "/images/Toyota-White.webp"},
      {"car_name": "Camry", "brand": "Toyota", "price": 27999, "color": "Black", "image": "/images/Camry-black.webp"},
      {"car_name": "Accord", "brand": "Honda", "price": 28999, "color": "Gray", "image": "/images/Accord-Gray.webp"},
      {"car_name": "X5", "brand": "BMW", "price": 60999, "color": "Blue", "image": "/images/Bmw-x5-Blue.webp"},
      {"car_name": "A4", "brand": "Audi", "price": 42999, "color": "Black", "image": "images/Audi-A4.webp"},
      {"car_name": "C-Class", "brand": "Mercedes-Benz", "price": 45999, "color": "Gray", "image": "images/Mercedes.webp"},
      {"car_name": "Altima", "brand": "Nissan", "price": 25999, "color": "Red", "image": "/images/Nissan-altima-red.webp"},
      {"car_name": "Challenger", "brand": "Dodge", "price": 58999, "color": " White", "image": "/images/Dodge-White.webp"},
      {"car_name": "Cherokee", "brand": "Jeep", "price": 34999, "color": "White", "image": "/images/Jeep-White.webp"},
      {"car_name": "Tucson", "brand": "Hyundai", "price": 30999, "color": "Blue", "image": "/images/Tucson-Blue.webp"},
      {"car_name": "Elantra", "brand": "Hyundai", "price": 22999, "color": "White", "image": "/images/Elantra-white.webp"},
      {"car_name": "RX", "brand": "Lexus", "price": 50999, "color": "Silver", "image": "/images/Lexus-Silver.webp"},
      {"car_name": "Range Rover", "brand": "Land Rover", "price": 90999, "color": "Green", "image": "/images/Rangerover-green.webp"},
      {"car_name": "Outback", "brand": "Subaru", "price": 32999, "color": "Green", "image": "/images/Outback-Green.webp"},
      {"car_name": "Impreza", "brand": "Subaru", "price": 22999, "color": "Blue", "image": "/images/Impreza-Blue.webp"},
      {"car_name": "Tiguan", "brand": "Volkswagen", "price": 33999, "color": "Silver", "image": "/images/Tiguan.webp"},
      {"car_name": "Golf", "brand": "Volkswagen", "price": 24999, "color": "White", "image": "/images/Golf-White.webp"},
      {"car_name": "Chiron", "brand": "Bugatti", "price": 2999999, "color": "Silver", "image": "/images/Chiron-Silver.webp"},
      {"car_name": "Veyron", "brand": "Bugatti", "price": 1999999, "color": "Yellow", "image": "/images/Veyron-Yellow.webp"},
      {"car_name": "Ghibli", "brand": "Maserati", "price": 74999, "color": "Yellow", "image": "/images/Maserati.webp"},
      {"car_name": "Levante", "brand": "Maserati", "price": 82999, "color": "Red", "image": "/images/Maserati_Levante-Red.webp"},
      {"car_name": "XC90", "brand": "Volvo", "price": 57999, "color": "Blue", "image": "/images/Volvo-Black.webp"},
      {"car_name": "S90", "brand": "Volvo", "price": 50999, "color": "Black", "image": "/images/Volvo-s90-Blue.webp"},
      {"car_name": "DB11", "brand": "Aston Martin", "price": 219999, "color": "Green", "image": "/images/Astonmartin-db11-Green.webp"},
      {"car_name": "Huracan", "brand": "Lamborghini", "price": 249999, "color": "Green", "image": "/images/Huracan_Green.webp"},
      {"car_name": "911", "brand": "Porsche", "price": 129999, "color": "Red", "image": "/images/Porsche-Red.webp"}
    ]
    export default carsData;
  
  